FROM pytorch/pytorch:1.8.1-cuda10.2-cudnn7-runtime 
RUN apt update && apt install build-essential ffmpeg libsm6 libxext6 git vim -y

ADD requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

